name: Deploy Blazor Web App

on:
  push:
    branches:
      - publish

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up .NET SDK (required for building Blazor WebAssembly)
    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'

    # Define a variable for the solution path
    - name: Set solution path
      run: echo "SOLUTION_PATH=SqlScriptsComparer/SqlScriptsComparer.sln" >> $GITHUB_ENV

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_PATH }}

    # Build the Blazor WebAssembly app
    - name: Build Blazor WebAssembly app
      run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release

    # Publish the app to the 'docs' folder
    - name: Publish Blazor WebAssembly app
      run: dotnet publish ${{ env.SOLUTION_PATH }} -c Release -o ./docs

    # Set up Git for pushing the changes
    - name: Set up Git user
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"

    # Commit and push the changes to the 'publish' branch
    - name: Commit and push changes
      run: |
        git add docs/
        git commit -m "Deploy Blazor app to docs folder"
        git push origin publish