name: Deploy Blazor Web App

permissions:
  contents: write  # Grant permission to push changes

on:
  push:
    branches:
      - publish

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up .NET SDK (required for building Blazor WebAssembly)
    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'

    # Define a variable for the solution path
    - name: Set solution path
      run: echo "SOLUTION_PATH=SqlScriptsComparer/SqlScriptsComparer.sln" >> $GITHUB_ENV

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_PATH }}

    # Build the Blazor WebAssembly app
    - name: Build Blazor WebAssembly app
      run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release

    # Publish the app to the 'docs' folder
    - name: Publish Blazor WebAssembly app
      run: dotnet publish ${{ env.SOLUTION_PATH }} -c Release -o ./docs

    # Commit and push the changes to the 'publish' branch
    - name: Commit and push changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: 'GitHub Actions'
        author_email: 'actions@github.com'
        message: 'Deploy Blazor WebApp to docs folder'
        add: 'docs/*'  # Add changes in docs folder
        